title: Gapuchi's Blog
email: arjun.adhia@gmail.com
description: >-
  I am a software developer. This is my blog. Check it out. Or don't. I'm not a cop.
baseurl: ""
url: "https://arjun.adhia.net"
twitter_username: waitIGotAnAdhia
github_username:  gapuchi

# Build settings
remote_theme: broccolini/swiss
theme_color: blue	
plugins:
  - jekyll-remote-theme

collections:
  machine_learning:
    sort_by: part
  system_design:
    sort_by: part
    output: true
  data_structures:
    sort_by: part
    output: true
  containers:
    sort_by: part
    output: true
  rust:
    sort_by: part
    output: true