theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: blue
  font:
    code: Fira Code
  features:
    - navigation.tracking
    - navigation.tabs

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

repo_url: https://github.com/gapuchi/gapuchi.github.io

site_name: Gapuchi's Notes
site_url: https://arjun.adhia.net/
site_description: Notes By Gapuchi
site_author: gapuchi